/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["UserController_getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user */
        patch: operations["UserController_updateUser"];
        trace?: never;
    };
    "/api/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get words */
        get: operations["WordsController_getWords"];
        put?: never;
        /** Create word */
        post: operations["WordsController_createWord"];
        /** Delete words */
        delete: operations["WordsController_deleteWords"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update words status */
        patch: operations["WordsController_updateWordsStatus"];
        trace?: never;
    };
    "/api/words/{wordId}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add translations to word */
        post: operations["WordsController_addWordTranslations"];
        /** Delete translations from word */
        delete: operations["WordsController_deleteWordTranslations"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserPayloadDto: {
            /**
             * @description Active learning language code
             * @example en
             */
            active_learning_language?: string;
            /**
             * @description Interface language code
             * @example en
             */
            interface_language?: string;
            /**
             * @description Native language code
             * @example ru
             */
            native_language?: string;
            /**
             * @description Theme preference
             * @example system
             * @enum {string}
             */
            theme?: "system" | "dark" | "light";
        };
        UpdateUserResponse: {
            /**
             * @description User ID
             * @example uuid
             */
            id: string;
            /**
             * @description Active learning language code
             * @example en
             */
            active_learning_language: string;
            /**
             * @description Interface language code
             * @example en
             */
            interface_language: string;
            /**
             * @description Native language code
             * @example ru
             */
            native_language: string;
            /**
             * @description Theme preference
             * @example system
             * @enum {string}
             */
            theme: "system" | "dark" | "light";
        };
        GetUserResponse: {
            /**
             * @description User ID
             * @example uuid
             */
            id: string;
            /**
             * @description Active learning language code
             * @example en
             */
            active_learning_language: string;
            /**
             * @description Interface language code
             * @example en
             */
            interface_language: string;
            /**
             * @description Native language code
             * @example ru
             */
            native_language: string;
            /**
             * @description Theme preference
             * @example system
             * @enum {string}
             */
            theme: "system" | "dark" | "light";
        };
        UpdateUserRequest: {
            /** @description Partial user data to update */
            payload: components["schemas"]["UpdateUserPayloadDto"];
        };
        TranslationResponseDto: {
            /**
             * @description Translation ID
             * @example uuid
             */
            id: string;
            /**
             * @description Translation text
             * @example привет
             */
            text: string;
            /**
             * @description Translation language code
             * @example ru
             */
            language: string;
        };
        WordWithTranslationsDto: {
            /**
             * @description Word ID
             * @example uuid
             */
            id: string;
            /**
             * @description Creation timestamp
             * @example 2024-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Update timestamp
             * @example 2024-01-01T00:00:00Z
             */
            updated_at: string;
            /**
             * @description User ID
             * @example uuid
             */
            user_id: string;
            /**
             * @description Word language code
             * @example en
             */
            language: string;
            /**
             * @description Word text
             * @example hello
             */
            text: string;
            /**
             * @description Sort ID for ordering
             * @example 1
             */
            sort_id: number;
            /**
             * @description Word status
             * @example New
             * @enum {string}
             */
            status: "New" | "Learn" | "Learned";
            /** @description Array of translations */
            translations: components["schemas"]["TranslationResponseDto"][];
        };
        FetchWordsResponse: {
            /** @description Array of words with translations */
            words: components["schemas"]["WordWithTranslationsDto"][];
            /**
             * @description Token for next page pagination
             * @example 10
             */
            nextPageToken: number | null;
        };
        CreateWordResponse: {
            /**
             * @description Word ID
             * @example uuid
             */
            id: string;
            /**
             * @description Creation timestamp
             * @example 2024-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Update timestamp
             * @example 2024-01-01T00:00:00Z
             */
            updated_at: string;
            /**
             * @description User ID
             * @example uuid
             */
            user_id: string;
            /**
             * @description Word language code
             * @example en
             */
            language: string;
            /**
             * @description Word text
             * @example hello
             */
            text: string;
            /**
             * @description Sort ID for ordering
             * @example 1
             */
            sort_id: number;
            /**
             * @description Word status
             * @example New
             * @enum {string}
             */
            status: "New" | "Learn" | "Learned";
            /** @description Array of translations */
            translations: components["schemas"]["TranslationResponseDto"][];
        };
        WordResponseDto: {
            /**
             * @description Word ID
             * @example uuid
             */
            id: string;
            /**
             * @description Creation timestamp
             * @example 2024-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Update timestamp
             * @example 2024-01-01T00:00:00Z
             */
            updated_at: string;
            /**
             * @description User ID
             * @example uuid
             */
            user_id: string;
            /**
             * @description Word language code
             * @example en
             */
            language: string;
            /**
             * @description Word text
             * @example hello
             */
            text: string;
            /**
             * @description Sort ID for ordering
             * @example 1
             */
            sort_id: number;
            /**
             * @description Word status
             * @example New
             * @enum {string}
             */
            status: "New" | "Learn" | "Learned";
        };
        UpdateWordsStatusResponse: {
            /** @description Array of updated words */
            words: components["schemas"]["WordResponseDto"][];
        };
        DeleteWordsResponse: {
            /** @description Array of deleted words */
            words: components["schemas"]["WordResponseDto"][];
        };
        AddWordTranslationsResponse: {
            /** @description Array of added translations */
            translations: components["schemas"]["TranslationResponseDto"][];
        };
        DeleteWordTranslationsResponse: {
            /** @description Array of deleted translations */
            translations: components["schemas"]["TranslationResponseDto"][];
        };
        WordDto: {
            /**
             * @description Language code
             * @example en
             */
            language: string;
            /**
             * @description Word text
             * @example hello
             */
            text: string;
        };
        TranslationDto: {
            /**
             * @description Translation text
             * @example привет
             */
            text: string;
            /**
             * @description Translation language code
             * @example ru
             */
            language: string;
        };
        CreateWordRequest: {
            /** @description Word information */
            word: components["schemas"]["WordDto"];
            /** @description Array of translations */
            translations: components["schemas"]["TranslationDto"][];
        };
        UpdateWordsStatusRequest: {
            /**
             * @description Array of word IDs
             * @example [
             *       "uuid1",
             *       "uuid2"
             *     ]
             */
            wordsIds: string[];
            /**
             * @description New status for words
             * @example New
             * @enum {string}
             */
            status: "New" | "Learn" | "Learned";
        };
        DeleteWordsRequest: {
            /**
             * @description Array of word IDs to delete
             * @example [
             *       "uuid1",
             *       "uuid2"
             *     ]
             */
            wordIds: string[];
        };
        AddWordTranslationsRequest: {
            /** @description Array of translations to add */
            translations: components["schemas"]["TranslationDto"][];
        };
        DeleteWordTranslationsRequest: {
            /**
             * @description Array of translation IDs to delete
             * @example [
             *       "uuid1",
             *       "uuid2"
             *     ]
             */
            translationsIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponse"];
                };
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateUserResponse"];
                };
            };
        };
    };
    WordsController_getWords: {
        parameters: {
            query: {
                /** @description Language code */
                language: string;
                /** @description Number of items per page */
                pageSize: number;
                /** @description Page token for pagination */
                pageToken?: number;
                /** @description Filter by word text */
                filterText?: string;
                /** @description Filter by word status */
                filterStatus?: "New" | "Learn" | "Learned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Words retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchWordsResponse"];
                };
            };
        };
    };
    WordsController_createWord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWordRequest"];
            };
        };
        responses: {
            /** @description Word created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWordResponse"];
                };
            };
        };
    };
    WordsController_deleteWords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteWordsRequest"];
            };
        };
        responses: {
            /** @description Words deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWordsResponse"];
                };
            };
        };
    };
    WordsController_updateWordsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWordsStatusRequest"];
            };
        };
        responses: {
            /** @description Words status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateWordsStatusResponse"];
                };
            };
        };
    };
    WordsController_addWordTranslations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Word ID */
                wordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWordTranslationsRequest"];
            };
        };
        responses: {
            /** @description Translations added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddWordTranslationsResponse"];
                };
            };
        };
    };
    WordsController_deleteWordTranslations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Word ID */
                wordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteWordTranslationsRequest"];
            };
        };
        responses: {
            /** @description Translations deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWordTranslationsResponse"];
                };
            };
        };
    };
}
