name: pnpm-install

on:
  workflow_call:

jobs:
  pnpm-install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install
