name: pnpm-install

on:
  workflow_call:

jobs:
  pnpm-install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          frozen-lockfile: 'true'
