name: Pre-commit checks

on:
  workflow_call:

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Derive SHAs for base and head
        uses: nrwl/nx-set-shas@v4

      - name: Run lint
        run: pnpm nx affected -t lint

  stylelint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Derive SHAs for base and head
        uses: nrwl/nx-set-shas@v4

      - name: Run stylelint
        run: pnpm nx affected -t stylelint

  typecheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Derive SHAs for base and head
        uses: nrwl/nx-set-shas@v4

      - name: Run typecheck
        run: pnpm nx affected -t typecheck

  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Derive SHAs for base and head
        uses: nrwl/nx-set-shas@v4

      - name: Run unit-tests
        run: pnpm nx affected -t test:unit:ci

  find-circular-deps:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Derive SHAs for base and head
        uses: nrwl/nx-set-shas@v4

      - name: Run circular-deps
        run: pnpm nx affected -t circular-deps

  find-unused:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run knip
        run: pnpm run knip

  check-dependency-versions:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check dependency versions
        run: pnpm run deps:check
# #  TODO: is all har sanitized?
# #  TODO: is i18n extracted?
