name: Pull request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  npm-ci:
    name: "npm ci"
    uses: ./.github/workflows/npm-ci.yml

  deploy:
    name: "Deploy staging"
    uses: ./.github/workflows/deploy.yml
    secrets:
      SA_DEPLOYER_PRIVATE_KEY: ${{ secrets.SA_STAGING_DEPLOYER_PRIVATE_KEY }}
    with:
      revision_name: pr-${{ github.event.pull_request.number }}
      cloud_id: b1g9utblfaj1k8am3nmg
      folder_name: languages-learner
      sa_deployer_id: ajelfqpn1n9hn128gsc4
      container_registry_id: crp7sst4j2jnr7n52g3g

  precommit-checks:
    name: "Pre-commit checks"
    needs: npm-ci
    uses: ./.github/workflows/precommit-checks.yml

  components-tests:
    name: "Components tests"
    needs: npm-ci
    uses: ./.github/workflows/components-tests.yml

  check-pr-title:
    name: "Check PR title"
    uses: ./.github/workflows/check-pr-title.yml
