name: Deploy

on:
  workflow_call:
    secrets:
      S3_KEY_ID:
        required: true
        description: S3 key ID
      S3_SECRET_KEY:
        required: true
        description: S3 secret key
    inputs:
      dest_path:
        type: string
        description: Destination S3 URL
        required: true
      pr_number:
        description: Pull request number
        type: string
        required: false

jobs:
  deploy-storybook:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Build storybook
        run: pnpm --filter @languages-learner/storybook run build

      - name: Deploy storybook build to s3
        uses: ./.github/actions/upload-to-s3
        with:
          source_path: apps/storybook/dist-storybook
          dest_path: ${{ inputs.dest_path }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Create Comment
        if: inputs.pr_number != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ inputs.pr_number }}
          header: storybook
          recreate: true
          message: |
            📚 Storybook deployed successfully!
            **Storybook URL:** https://languages-learner-static.website.yandexcloud.net${{ inputs.dest_path }}/index.html

